services:
  - type: web
    name: stock-chat-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn stockchat.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: stockchat.settings
      - key: SECRET_KEY
        value: $djy&v)k^^owk%clqu!=80^s##s4of@+b0&sf(xlu080kjzzob
